### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by rasmusviben** [dineeek/ngx-numeric-range-form-field#1]
Hi,

Would it be possible to have this updated to support angular 13? :) Currently it looks like it's stuck on angular 11. 

**npm ERR! Found: @angular/common@13.1.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.1.2" from ngx-numeric-range-form-field@1.0.3
npm ERR! node_modules/ngx-numeric-range-form-field
npm ERR!   ngx-numeric-range-form-field@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.**

**Comment by dineeek** [comment]
Hi, [rasmusviben](https://github.com/rasmusviben)! 

The library has been updated to Angular 13v. Update the library to the 2.0.0 version so you can use it.
