### ISSUE TITLE
Error: Cannot resolve type entity i16.NgxNumericRangeFormFieldModule to symbol

### ISSUE THREAD

**Issue by NirArgil** [dineeek/ngx-numeric-range-form-field#4]
Hi get this Error.
Please tell me how to fix it.

the Error above:
Error: Cannot resolve type entity i16.NgxNumericRangeFormFieldModule to symbol

Thank you.

**Comment by dineeek** [comment]
Hi NirArgil,

this error seems to be on your side. Please refer to this solution:
https://stackoverflow.com/a/70585774

Thanks!
