### ISSUE TITLE
ERROR Error: NG01002: Must supply a value for form control with name: 'minimum'

### ISSUE THREAD

**Issue by NirArgil** [dineeek/ngx-numeric-range-form-field#5]
Hi,
get this Error in the console after this component rendered;

ERROR Error: NG01002: Must supply a value for form control with name: 'minimum'

Can you fix it please?

**Comment by dineeek** [comment]
Hi NirArgil,

the error is on your side. Please refer to the documentation on how to assign value to a form.

`
		this.form = new FormGroup({
			range: new FormControl({ minimum: 10, maximum: 59 } as INumericRange),
		});
`
