### ISSUE TITLE
Add 'minReadonly' and 'maxReadonly' inputs to the component

### ISSUE THREAD

**Issue by Oubayda-Khayata** [dineeek/ngx-numeric-range-form-field#6]
## Description:

I think that this component is very useful in many cases. However, adding the 'readonly' support for the min and max fields separately makes it more general.

## How does it work?

If the current 'readonly' input is set to 'true', then the min and max fields are disabled whatever the values of 'minReadonly' and 'maxReadonly' are.
If the current 'readonly' input is set to 'false', then the 'minReadonly' and the 'maxReadonly' inputs control whether the min or max fields are read-only or not, respectively.

## Example:

![image](https://user-images.githubusercontent.com/17801490/183298282-9049c56b-4643-4d19-80f0-87c542847f35.png)
*The min field is read-only*

**Comment by dineeek** [comment]
Hi Oubayda-Khayata,

the readonly property for minimum and maximum input is now supported in version 2.2.0.
Thanks for using the library and further suggestions are welcome. 

Thanks!

**Comment by Oubayda-Khayata** [comment]
Thank you @dineeek for your fast update and response!
I'm really happy to find this library after a lot of searching.

Thanks!
